### ISSUE TITLE
Inline LaTex Support?

### ISSUE THREAD

**Issue by navvye** [RomanHauksson/academic-project-astro-template#1]
I was just wondering if there's support for inline LaTex? I tried rendering equations using KaTex, but it always wraps the equation onto the next line rather than rendering it with the rest of the text. This can get quite annoying sometimes, and I've had to come up with a hacky solution for this.

**Comment by RomanHauksson** [comment]
Thanks for the issue! Just added inline LaTeX support. Example use:

```tsx
<div>This is text in a paragraph, followed by an equation, <LaTeX inline formula="a^2 + b^2 = c^2" />, and then more text.</div>
```

**Comment by navvye** [comment]
Thanks!
