### ISSUE TITLE
Custom width and background configuration

### ISSUE THREAD

**Issue by RyanLi0802** [RomanHauksson/academic-project-astro-template#2]
Hi,

Is it possible to configure custom column width and background colors (e.g., alternating between white and gray) for different text sections?

In the current demo, it seems all sections have the same fixed width, which looks a little bit too narrow on my computer screen. Also, I couldn't find a way to say make the abstract have a different style or color from the rest of the sections.

Thanks so much!

**Comment by RomanHauksson** [comment]
Thanks for submitting this issue! I added a new component called `HighlightedSection`, which has a customizable background color (gray by default):

```mdx
import HighlightedSection from "../components/HighlightedSection.astro";

<HighlightedSection>

## Abstract

Here's the abstract of my paper.

</HighlightedSection>
```

Custom background color:

```mdx
import HighlightedSection from "../components/HighlightedSection.astro";

<HighlightedSection color="#fcd34d">

## Abstract

Here's the abstract of my paper.

</HighlightedSection>
```

If you clicked "Use this template" to start your repository, go ahead and click it again to make a new copy with the most recent changes. If you forked it, follow [these instructions](https://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository), and if you cloned it, you can just pull the changes.

To change the width of the content, you have to edit the `Layout` component and the `HighlightedSection` component.

1. In `src/layouts/Layout.astro`, the `*:max-w-[60rem]` class on the body element gives every child a maximum width of 60 rem:
```html
<body class="flex flex-col gap-4 items-center pt-12 pb-6 w-full *:px-6 *:max-w-[60rem]">
```  
2. Similarly, in `src/components/HighlightedSection.astro`:
```html
<div class="flex flex-col gap-4 items-center w-full max-w-[60rem] [&>h2]:mt-0 px-6">
```
