### ISSUE TITLE
How do I add a hugging face icon?

### ISSUE THREAD

**Issue by luoxue-star** [RomanHauksson/academic-project-astro-template#8]
Hi, thanks for your excellent work!
Could you please tell me how to add a hugging face icon like the github icon?

**Comment by RomanHauksson** [comment]
Thanks! This template uses [Astro Icon](https://www.astroicon.dev/) library for icons.

1. Search on [Iconify](https://icon-sets.iconify.design/) to find the icon you want. For your case, I found one called `simple-icons:huggingface`, from the Simple Icons icon set.
2. Install the corresponding icon set: `npm install @iconify-json/simple-icons`.
3. If you're using the icon in one of the link buttons, add it in one of the objects in the `links` prop of the `<Header />` component in `index.mdx`:
```
    {
      name: "Hugging Face",
      url: "https://huggingface.co/",
      icon: "simple-icons:huggingface"
    }
```
